language: java

before_install:
- openssl aes-256-cbc -K $encrypted_c869e7205488_key -iv $encrypted_c869e7205488_iv
  -in secrets.gradle.enc -out secrets.gradle -d
- chmod +x gradlew

install:
- "./gradlew wrapper"

script:
- "./gradlew uploadIcons"
